name: test
on:
  workflow_dispatch:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: extractions/setup-just@v2
      - name: get the code
        uses: actions/checkout@v4
      - name: install golang
        uses: actions/setup-go@v5
        with:
          go-version-file: "go.mod"
      - name: run the tests
        run: just test
  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: extractions/setup-just@v2
      - name: get the code
        uses: actions/checkout@v4
      - name: install golang
        uses: actions/setup-go@v5
        with:
          go-version-file: "go.mod"
      - name: build
        run: just build
      - name: deploy
        run: echo "deploying the project..."

  docker:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Log in to Docker registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/portfolio:latest
